### ISSUE TITLE
Cannot Edit Extension 

### ISSUE THREAD

**Issue by Candunc** [andyvr/braintree-payments#1]
Hello, I just installed this to my server and copied over the admin, catalog and vendor folders. I clicked install in the Admin -> Extensions -> Payments folder, however php reports the following error:

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 20

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 22

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 23

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 24

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 25

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 26

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 27

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 28

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 30

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 31

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 32

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 33

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 34Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 35

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 36

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 37

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 38

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 39

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 40

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 42

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 43

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 48

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 54

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 60

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 65

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 70

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 73

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 75

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 81

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 87

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 93

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 95

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 100

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 106

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 112

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 118

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 124

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 130

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 136

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 141

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 146

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 151

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 156

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 162

Notice: Indirect modification of overloaded property ControllerPaymentSimpleBraintreePayments::$data has no effect in /var/www/OpenCart/admin/controller/payment/simple_braintree_payments.php on line 168

**Comment by andyvr** [comment]
Sorry, but the extension is not compatible with Opencart 2.
